### ISSUE TITLE
Grid is no longer working (OS X Yosemite)

### ISSUE THREAD

**Issue by MecoKing** [robrix/Grid#11]
_Sad Face_

**Comment by fr-anthony** [comment]
I had to go into `Security & Privacy → Privacy → Accessibility`, authenticate by clicking the lock, and then check the box allowing Grid to control the computer. After that, Grid works again. Hope this helped!

**Comment by MecoKing** [comment]
Thanks, when grid broke I was crippled!

**Comment by robrix** [comment]
Aha, thanks :sparkles: Closing this out!
