### ISSUE TITLE
Code Sign error: The identity '3rd Party Mac Developer Application' doesn't match any valid, non-expired certificate/private key pair in your keychains

### ISSUE THREAD

**Issue by Haefler1985** [robrix/Grid#9]
I don't have a clue what that means. Just added your repository to my xcode and pressed run to build Grid...

![Bildschirmfoto 2013-02-03 um 12 57 17](https://f.cloud.github.com/assets/3462910/121786/f40ab830-6df8-11e2-9f27-a970933bab7f.png)

**Comment by robrix** [comment]
What branch are you on? I think this has been fixed in develop but I need to double-check that.

**Comment by Haefler1985** [comment]
Sorry, my mistake. I was on the wrong branch...

**Comment by Haefler1985** [comment]
Hmm. Still don't get a binary...

``` C
dyld: Symbol not found: _OBJC_CLASS_$_NSObject
  Referenced from: /Users/Benni/Library/Developer/Xcode/DerivedData/Grid-aduidjjbkfocbmfeflahwdtyntrf/Build/Products/Debug/Haxcessibility.framework/Versions/A/Haxcessibility
  Expected in: /usr/lib/libobjc.A.dylib
 in /Users/Benni/Library/Developer/Xcode/DerivedData/Grid-aduidjjbkfocbmfeflahwdtyntrf/Build/Products/Debug/Haxcessibility.framework/Versions/A/Haxcessibility
(lldb) 
```

**Comment by robrix** [comment]
Should just be able to build now.

**Comment by robrix** [comment]
(Note that `master` is the current branch.)
